RESOLUTION = (1280, 800)
AA = True

FONT = 'evesansneue-regular.otf'
BIG_FONT_SIZE = 50
MEDIUM_FONT_SIZE = 30
SMALL_FONT_SIZE = 20
MINI_FONT_SIZE = 15

N_TIERS = 6
N_SHIP_COPIES_PER_TIER = (18, 15, 15, 12, 9, 6)
N_MARKET_SHIPS_PER_TIER = (4, 5, 6, 7, 8, 9)
N_MARKET_SHIPS_PER_ROW = 3

SHIP_ICON_SIZE = (100, 100)
SHIP_ICON_PADDING = (20, 20)
MARKET_ICON_SIZE = (100, 100)
MARKET_ICON_PADDING = (50, 20)
MARKET_CONTROL_OFFSET = (100, 50)
MARKET_OFFSET = (MARKET_CONTROL_OFFSET[0] + MARKET_ICON_SIZE[0] + MARKET_ICON_PADDING[0], MARKET_CONTROL_OFFSET[1])
UPGRADE_TIER_ICON_POS = (MARKET_CONTROL_OFFSET[0], MARKET_CONTROL_OFFSET[1])
RECYCLE_ICON_POS = (MARKET_CONTROL_OFFSET[0], UPGRADE_TIER_ICON_POS[1] + MARKET_ICON_SIZE[1] + MARKET_ICON_PADDING[1])
HOLD_ICON_POS = (MARKET_CONTROL_OFFSET[0], RECYCLE_ICON_POS[1] + MARKET_ICON_SIZE[1] + MARKET_ICON_PADDING[1])
HOVER_PADDING = (75, 0)
HOVER_SHIP_STATS_POS = (MARKET_OFFSET[0] + N_MARKET_SHIPS_PER_ROW*(SHIP_ICON_SIZE[0] + SHIP_ICON_PADDING[0]) + HOVER_PADDING[0], MARKET_CONTROL_OFFSET[1])
HOVER_SHIP_STATS_SIZE = (500, (N_MARKET_SHIPS_PER_TIER[-1] // N_MARKET_SHIPS_PER_ROW)*(SHIP_ICON_SIZE[1] + SHIP_ICON_PADDING[1]) - SHIP_ICON_PADDING[1])

STATS_OVERLAY_BG_COLOR = (38, 38, 38)
OVERLAY_ALPHA = 150
OVERLAY_SHIP_ICON_SIZE = (200, 200)
OVERLAY_SHIP_ICON_POS = (HOVER_SHIP_STATS_POS[0], HOVER_SHIP_STATS_POS[1])
OVERLAY_FONT_COLOR = (255, 255, 255)
OVERLAY_FONT_ANTIALIASING = True
OVERLAY_TEXT_PADDING = (20, 50)
OVERLAY_SHIP_NAME_POS = (OVERLAY_SHIP_ICON_POS[0] + OVERLAY_SHIP_ICON_SIZE[0] + OVERLAY_TEXT_PADDING[0], OVERLAY_SHIP_ICON_POS[1] + OVERLAY_TEXT_PADDING[1])
OVERLAY_SHIP_RACE_POS = (OVERLAY_SHIP_NAME_POS[0], OVERLAY_SHIP_NAME_POS[1] + OVERLAY_TEXT_PADDING[1])
OVERLAY_SHIP_ATTACK_POS = (OVERLAY_SHIP_ICON_POS[0] + OVERLAY_TEXT_PADDING[0], HOVER_SHIP_STATS_POS[1] + OVERLAY_SHIP_ICON_SIZE[1])
OVERLAY_SHIP_SHIELDS_POS = (OVERLAY_SHIP_ATTACK_POS[0], OVERLAY_SHIP_ATTACK_POS[1] + SMALL_FONT_SIZE)
OVERLAY_SHIP_ARMOR_POS = (OVERLAY_SHIP_ATTACK_POS[0], OVERLAY_SHIP_SHIELDS_POS[1] + SMALL_FONT_SIZE)
OVERLAY_SHIP_HULL_POS = (OVERLAY_SHIP_ATTACK_POS[0], OVERLAY_SHIP_ARMOR_POS[1] + SMALL_FONT_SIZE)
OVERLAY_TIER_ICON_SIZE = (40, 40)

STATION_HEALTH = 100
N_SHIPS_PER_PLAYER = 10
BOARD_SIZE = (5, 2)
TILE_SIZE = (100, 100)
TILE_PADDING = (35, 35)
BOARD_OFFSET = (0.5*RESOLUTION[0] - 2.5*TILE_SIZE[0] - 2*TILE_PADDING[0], 0.5*RESOLUTION[1] + TILE_PADDING[1])

BATTLE_TILE_PADDING = (100, 60)
BATTLE_BOARD_OFFSET_P1 = (0.5*RESOLUTION[0] - 2.5*TILE_SIZE[0] - 2*BATTLE_TILE_PADDING[0], 0.5*RESOLUTION[1] + BATTLE_TILE_PADDING[1])
BATTLE_BOARD_OFFSET_P2 = (0.5*RESOLUTION[0] - 2.5*TILE_SIZE[0] - 2*BATTLE_TILE_PADDING[0], 0.5*RESOLUTION[1] - 2*(BATTLE_TILE_PADDING[1] + TILE_SIZE[1]))

REPROCESS_SIZE = (150, 150)
REPROCESS_PADDING = (50, (2*(TILE_SIZE[1] + 0.5*TILE_PADDING[1]) - REPROCESS_SIZE[1])/2)
REPROCESS_POS = (BOARD_OFFSET[0] + 5*(TILE_SIZE[0] + TILE_PADDING[0]) + REPROCESS_PADDING[0], BOARD_OFFSET[1] + REPROCESS_PADDING[1])

HUMAN = 0
COMPUTER = 1

END_TURN_SIZE = (200, 50)
END_TURN_PADDING = (20, 20)
END_TURN_POS = (RESOLUTION[0] - END_TURN_SIZE[0] - END_TURN_PADDING[0], RESOLUTION[1] - END_TURN_SIZE[1] - END_TURN_PADDING[1])
END_TURN_COLOR = (38, 38, 38)
END_TURN_ALPHA = 150
END_TURN_FONT_COLOR = (0, 255, 0)
END_TURN_FONT_ANTIALIASING = OVERLAY_FONT_ANTIALIASING
END_TURN_TEXT = 'ENTER BATTLE'

STARTING_PLEX = 3
PLEX_ICON_SIZE = (30, 30)
PLEX_PADDING = (75, 0)
PLEX_POS = (MARKET_CONTROL_OFFSET[0] + PLEX_PADDING[0], END_TURN_POS[1] + PLEX_PADDING[1])
MAX_PLEX = 10
SHIP_COST = 3
SHIP_REPROCESS = 1
RECYCLE_COST = 1
UPGRADE_COST = (5, 7, 8, 9, 11)
PLEX_FONT_ANTIALIASING = OVERLAY_FONT_ANTIALIASING
PLEX_FONT_COLOR = (255, 196, 71)
PLEX_TEXT_PADDING = (25, (PLEX_ICON_SIZE[1] - SMALL_FONT_SIZE)//2)
PLEX_TEXT_POS = (MARKET_CONTROL_OFFSET[0] + PLEX_TEXT_PADDING[0], END_TURN_POS[1] + PLEX_TEXT_PADDING[1])
UPGRADE_TIER_PLEX_ICON_POS = (UPGRADE_TIER_ICON_POS[0] - PLEX_ICON_SIZE[0], UPGRADE_TIER_ICON_POS[1] + (MARKET_ICON_SIZE[1] - PLEX_ICON_SIZE[1])//3)
RECYCLE_PLEX_ICON_POS = (RECYCLE_ICON_POS[0] - PLEX_ICON_SIZE[0], RECYCLE_ICON_POS[1] + (MARKET_ICON_SIZE[1] - PLEX_ICON_SIZE[1])//3)
MISC_PLEX_TEXT_PADDING = (PLEX_ICON_SIZE[0] - SMALL_FONT_SIZE, PLEX_ICON_SIZE[1])

ORDER_TEXT_FONT_ANTIALIASING = OVERLAY_FONT_ANTIALIASING
ORDER_TEXT_FONT_COLOR = (255, 255, 255)

BLACK = (0, 0, 0)
GRAY = (38, 38, 38)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)

BATTLE_TILE_SIZE = (200, 200)
STATUS_SHIELDS_RADIUS = 68
STATUS_ARMOR_RADIUS = 62
STATUS_HULL_RADIUS = 56
STATUS_OUTLINE_THICKNESS = 1
STATUS_GRANULARITY_SHIELDS = 1
STATUS_GRANULARITY_ARMOR = 1
STATUS_GRANULARITY_HULL = 1
STATUS_INTERVALS = 75
START_ANGLE = 135
END_ANGLE = 45
TOTAL_ANGLE = 360 - (START_ANGLE - END_ANGLE)
EACH_ANGLE = TOTAL_ANGLE / STATUS_INTERVALS
THICKNESS_BETWEEN_ANGLES = 3
SHIP_ICON_BATTLE_PADDING = (10, 10)
SHIP_ICON_BATTLE_SIZE = (2*STATUS_SHIELDS_RADIUS + SHIP_ICON_BATTLE_PADDING[0], 2*STATUS_SHIELDS_RADIUS + SHIP_ICON_BATTLE_PADDING[1])

TITLE_FONT_SIZE = 100
TITLE_POS = (RESOLUTION[0]//2, RESOLUTION[1]//3)
MENU_FONT_SIZE = TITLE_FONT_SIZE // 3
MENU_0_POS = (TITLE_POS[0], RESOLUTION[1]//2 + RESOLUTION[1]//8)
MENU_1_POS = (MENU_0_POS[0], MENU_0_POS[1] + 1.5*MENU_FONT_SIZE)
MENU_2_POS = (MENU_0_POS[0], MENU_1_POS[1] + 1.5*MENU_FONT_SIZE)
MENU_3_POS = (MENU_0_POS[0], MENU_2_POS[1] + 1.5*MENU_FONT_SIZE)
MENU_SIZE = 4
START_GAME = 0
STATS = 1
TUTORIAL = 2
EXIT = 3

# game states
MENU = 0
GAME = 1
COMMANDER_SELECT = 2
MARKET = 3
BATTLE = 4

COMMANDER_SELECT_SIZE = (RESOLUTION[0]//5, RESOLUTION[0]//5)
N_COMMANDER_CHOICES = 3
COMMANDER_SELECT_ICON_POS = []
COMMANDER_NAME_POS = []
COMMANDER_RACE_POS = []
COMMANDER_BONUS_DESC_POS = []
COMMANDER_PENALTY_DESC_POS = []
COMMANDER_SELECT_INFO_RECT_POS = []
COMMANDER_PADDING = (RESOLUTION[0] - (N_COMMANDER_CHOICES * COMMANDER_SELECT_SIZE[0]))//(N_COMMANDER_CHOICES + 1)
for i in range(N_COMMANDER_CHOICES):
	COMMANDER_SELECT_ICON_POS.append((int((i + 1)*COMMANDER_PADDING + (0.5+i)*COMMANDER_SELECT_SIZE[0]), RESOLUTION[1]//3))
	COMMANDER_NAME_POS.append((COMMANDER_SELECT_ICON_POS[-1][0], COMMANDER_SELECT_ICON_POS[-1][1] + COMMANDER_SELECT_SIZE[1]//2 + MEDIUM_FONT_SIZE))
	COMMANDER_RACE_POS.append((COMMANDER_NAME_POS[-1][0], COMMANDER_NAME_POS[-1][1] + MEDIUM_FONT_SIZE))
	COMMANDER_BONUS_DESC_POS.append((COMMANDER_RACE_POS[-1][0] - COMMANDER_SELECT_SIZE[0]//2, COMMANDER_RACE_POS[-1][1] + 3*SMALL_FONT_SIZE))
	COMMANDER_PENALTY_DESC_POS.append((COMMANDER_BONUS_DESC_POS[-1][0], COMMANDER_BONUS_DESC_POS[-1][1] + 2*SMALL_FONT_SIZE))
	COMMANDER_SELECT_INFO_RECT_POS.append((COMMANDER_SELECT_ICON_POS[-1][0], RESOLUTION[1]//2))
COMMANDER_SELECT_INFO_RECT_SIZE = (RESOLUTION[0]//4, RESOLUTION[0]//2.15)
COMMANDER_SELECT_HIGHLIGHT_RECT_SIZE = (COMMANDER_SELECT_INFO_RECT_SIZE[0] + COMMANDER_PADDING//4, COMMANDER_SELECT_INFO_RECT_SIZE[1] + COMMANDER_PADDING//4)
