RESOLUTION = (1280, 800)

FONT = 'evesansneue-regular.otf'
BIG_FONT_SIZE = 50
MEDIUM_FONT_SIZE = 30
SMALL_FONT_SIZE = 20

N_TIERS = 6
N_SHIP_COPIES_PER_TIER = (18, 15, 15, 12, 9, 6)
N_MARKET_SHIPS_PER_TIER = (4, 5, 6, 7, 8, 9)
N_MARKET_SHIPS_PER_ROW = 3

SHIP_ICON_SIZE = (100, 100)
SHIP_ICON_PADDING = (20, 20)
MARKET_ICON_SIZE = (100, 100)
MARKET_ICON_PADDING = (50, 20)
MARKET_CONTROL_OFFSET = (100, 50)
MARKET_OFFSET = (MARKET_CONTROL_OFFSET[0] + MARKET_ICON_SIZE[0] + MARKET_ICON_PADDING[0], MARKET_CONTROL_OFFSET[1])
UPGRADE_TIER_ICON_POS = (MARKET_CONTROL_OFFSET[0], MARKET_CONTROL_OFFSET[1])
RECYCLE_ICON_POS = (MARKET_CONTROL_OFFSET[0], UPGRADE_TIER_ICON_POS[1] + MARKET_ICON_SIZE[1] + MARKET_ICON_PADDING[1])
HOLD_ICON_POS = (MARKET_CONTROL_OFFSET[0], RECYCLE_ICON_POS[1] + MARKET_ICON_SIZE[1] + MARKET_ICON_PADDING[1])
HOVER_PADDING = (75, 0)
HOVER_SHIP_STATS_POS = (MARKET_OFFSET[0] + N_MARKET_SHIPS_PER_ROW*(SHIP_ICON_SIZE[0] + SHIP_ICON_PADDING[0]) + HOVER_PADDING[0], MARKET_CONTROL_OFFSET[1])
HOVER_SHIP_STATS_SIZE = (500, (N_MARKET_SHIPS_PER_TIER[-1] // N_MARKET_SHIPS_PER_ROW)*(SHIP_ICON_SIZE[1] + SHIP_ICON_PADDING[1]) - SHIP_ICON_PADDING[1])

STATS_OVERLAY_BG_COLOR = (38, 38, 38)
OVERLAY_ALPHA = 150
OVERLAY_SHIP_ICON_SIZE = (200, 200)
OVERLAY_SHIP_ICON_POS = (HOVER_SHIP_STATS_POS[0], HOVER_SHIP_STATS_POS[1])
OVERLAY_FONT_COLOR = (255, 255, 255)
OVERLAY_FONT_ANTIALIASING = True
OVERLAY_TEXT_PADDING = (20, 50)
OVERLAY_SHIP_NAME_POS = (OVERLAY_SHIP_ICON_POS[0] + OVERLAY_SHIP_ICON_SIZE[0] + OVERLAY_TEXT_PADDING[0], OVERLAY_SHIP_ICON_POS[1] + OVERLAY_TEXT_PADDING[1])
OVERLAY_SHIP_RACE_POS = (OVERLAY_SHIP_NAME_POS[0], OVERLAY_SHIP_NAME_POS[1] + OVERLAY_TEXT_PADDING[1])
OVERLAY_SHIP_TIER_POS = (OVERLAY_SHIP_ICON_POS[0], OVERLAY_SHIP_RACE_POS[1] + OVERLAY_TEXT_PADDING[1])
OVERLAY_SHIP_SHIELDS_POS = (OVERLAY_SHIP_ICON_POS[0], OVERLAY_SHIP_TIER_POS[1] + OVERLAY_TEXT_PADDING[1])
OVERLAY_SHIP_ARMOR_POS = (OVERLAY_SHIP_ICON_POS[0], OVERLAY_SHIP_SHIELDS_POS[1] + OVERLAY_TEXT_PADDING[1])
OVERLAY_SHIP_HULL_POS = (OVERLAY_SHIP_ICON_POS[0], OVERLAY_SHIP_ARMOR_POS[1] + OVERLAY_TEXT_PADDING[1])
